#debug: false
#trace: false

#server.address=192.168.0.40
#server:
#  port: 8081
#  servlet:
#    contextPath: /${spring.application.name}
#spring:
#  application:
#    name: config
#  profiles:
#    active: subversion
#  cloud:
#    config:
#      server:
#        prefix: /svn
#        svn:
#          uri: ${htcf.svn.uri}
#          username: ${htcf.svn.username}
#          password: ${htcf.svn.password}
#          search-paths: '{application}/${htcf.profile:dev}'
#          default-label: trunk
#          basedir: E:/configRep #默认在系统临时目录下面，需要调整一下避免临时文件被系统自动清理
#        native:
#          search-locations: E:/configRep
#        overrides:
#          db: aaaaaaaaaaaaaaaaaaaaaaaaa
#  rabbitmq:
#    host: 192.168.0.81
#    port: 5670
#    username: admin
#    password: admin

#eureka:
#  instance:
#    preferIpAddress: true
#    #显示服务名
#    instance-id: ${spring.application.name}
#    #跳转swagger-ui.html
#    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}${server.servlet.contextPath}/swagger-ui.html
#    metadata-map:
#      configPath: ${server.servlet.contextPath:}
#      management.context-path: ${server.servlet.contextPath:}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8091/rc/eureka/
#    register-with-eureka: false
#    fetch-registry: false

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,refresh,bus-refresh
