spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #  session:
#    store-type: redis
  messages:
    basename: i18n/messages,org/springframework/security/messages
    encoding: UTF-8

server:
  servlet:
    session:
      timeout: 24h
      cookie:
        name: CASSESSION
    
fcf:
  index: 
    indexPath: redirect:http://localhost:8848/trunk/views/index.html
fcp:
  cas:
    filterSecurity: false
    loginPageUrl: /views/user/login.html
    anonymous:
    - /views/**
    - /layuiadmin/**
    - /frame/auth/**
    - /login/**
    - /login
    - /favicon.ico
    - /v2/api-docs
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - /actuator/**
    - /eureka/**
    - /repo/**
    - /console
    - /console/**
    - /test2/**
    
    webRequestMatchers:
    - /
    - /oauth/authorize
    - /login
    - /views/**
    - /layuiadmin/**
    - /logout
    - /actuator/**
    - /rc