debug: true

spring:
  application:
    name: generator
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
---
htcf:
  cache:
    enable: false
  esb:
    enable: false
  log:
    transaction:
      enable: false
    sql:
      enable: false
    access:
      enable: false
---
spring:
  cloud:
    bus:
      enabled: false
fcf:
  esb:
    enable: false
---
