debug: true

spring:
  application:
    name: generator
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
---
htcf:
  cache:
    enable: false
  esb:
    enable: false
  log:
    transaction:
      enable: false
    sql:
      enable: false
    access:
      enable: false
---
spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
---
#htcf:
#  enable-data-source: true
#  datasource:
#    main:
#      url: jdbc:p6spy:h2:file:./h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#      initial-size: 0
#      min-idle: 2
#      max-active: 5
#      max-wait: 6000
#      time-between-eviction-runs-millis: 3600000
#      min-evictable-idle-time-millis: 30000
#      validation-query: select 'x' from dual
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat
#      default: true
---
spring:
  cloud:
    bus:
      enabled: false
fcf:
  esb:
    enable: false
---
eureka:
  client:
    enabled: false
