fcf:
  redis:
    config:
      database: 15
      host: localhost
    rc:
      database: 14
    cas:
      database: 13
    gateway:
      database: 12
    basic:
      database: 11
    sso:
      database: 10
    apiGateway:
      database: 9
    admin:
      database: 8
    files:
      database: 7
    esb:
      database: 6
    rtp:
      database: 5
    system:
      database: 4

spring:
  redis:
    host: 192.168.168.100
    database: ${fcf.redis.${spring.application.name}.database:0}
    timeout: 2000ms
#    sentinel:
#      nodes: 192.168.0.71:28000,192.168.0.71:28001,192.168.0.71:28002
#      master: mymaster