spring:
  application:
    name: cas
---
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
---
# 环境中没有配置mq，临时关闭
# 正常情况下，本地不要存在任何配置
spring:
  cloud:
    bus:
      enabled: false
fcf:
  esb:
    enable: false
  mvc:
    cors:
      enable: true
  cache:
    enable: false