security:
  oauth2:
    client:
      # 客户端信息
      clientId: platform
      clientSecret: platform
      accessTokenUri: ${htcf.accessTokenUri:http://localhost:8084/cas/oauth/token}
      userAuthorizationUri:  ${htcf.userAuthorizationUri:http://localhost:8084/cas/oauth/authorize}
    resource:
      # 用户信息 url
      userInfoUri:  ${htcf.userInfoUri:http://localhost:8084/cas/userinfo}
      #preferTokenInfo: false
    authorization:
      check-token-access: ${htcf.checkTokenAccess:http://localhost:8084/cas/oauth/check_token}

