spring:
  application:
    name: task
---

fcp:
  task:
    job:
      adminAddresses: http://192.168.168.100:8892/xxl-job-admin
      appName: fcp-job-executor
      ip: 192.168.78.150
      port: 8892
      logPath: /data/applogs/xxl-job/jobhandler/
      logRetentionDays: -1